# Generated by Django 4.0.4 on 2022-05-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('Auteur', models.CharField(max_length=255, verbose_name='Author')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('number_of_pages', models.PositiveIntegerField(verbose_name='Number of pages')),
                ('resume', models.TextField(verbose_name='Resume')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Category name')),
            ],
        ),
    ]
